//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTApp.B2B {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Articolo", Namespace="http://schemas.datacontract.org/2004/07/NAVB2BService.Classi")]
    [System.SerializableAttribute()]
    public partial class Articolo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Descrizione1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Descrizione2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> GiacenzaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LottoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipologiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitaDiMisuraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codice {
            get {
                return this.CodiceField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceField, value) != true)) {
                    this.CodiceField = value;
                    this.RaisePropertyChanged("Codice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrizione1 {
            get {
                return this.Descrizione1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Descrizione1Field, value) != true)) {
                    this.Descrizione1Field = value;
                    this.RaisePropertyChanged("Descrizione1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrizione2 {
            get {
                return this.Descrizione2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Descrizione2Field, value) != true)) {
                    this.Descrizione2Field = value;
                    this.RaisePropertyChanged("Descrizione2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Giacenza {
            get {
                return this.GiacenzaField;
            }
            set {
                if ((this.GiacenzaField.Equals(value) != true)) {
                    this.GiacenzaField = value;
                    this.RaisePropertyChanged("Giacenza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Lotto {
            get {
                return this.LottoField;
            }
            set {
                if ((this.LottoField.Equals(value) != true)) {
                    this.LottoField = value;
                    this.RaisePropertyChanged("Lotto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipologia {
            get {
                return this.TipologiaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipologiaField, value) != true)) {
                    this.TipologiaField = value;
                    this.RaisePropertyChanged("Tipologia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitaDiMisura {
            get {
                return this.UnitaDiMisuraField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitaDiMisuraField, value) != true)) {
                    this.UnitaDiMisuraField = value;
                    this.RaisePropertyChanged("UnitaDiMisura");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/NAVB2BService.Classi")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> AttivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string B2BPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CAPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CittaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceFiscaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailEcommerceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HiddenPricePasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndirizzoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsHiddenPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitaIvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RagioneSocialeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipologiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Attivo {
            get {
                return this.AttivoField;
            }
            set {
                if ((this.AttivoField.Equals(value) != true)) {
                    this.AttivoField = value;
                    this.RaisePropertyChanged("Attivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string B2BPassword {
            get {
                return this.B2BPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.B2BPasswordField, value) != true)) {
                    this.B2BPasswordField = value;
                    this.RaisePropertyChanged("B2BPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CAP {
            get {
                return this.CAPField;
            }
            set {
                if ((object.ReferenceEquals(this.CAPField, value) != true)) {
                    this.CAPField = value;
                    this.RaisePropertyChanged("CAP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Citta {
            get {
                return this.CittaField;
            }
            set {
                if ((object.ReferenceEquals(this.CittaField, value) != true)) {
                    this.CittaField = value;
                    this.RaisePropertyChanged("Citta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codice {
            get {
                return this.CodiceField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceField, value) != true)) {
                    this.CodiceField = value;
                    this.RaisePropertyChanged("Codice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceFiscale {
            get {
                return this.CodiceFiscaleField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceFiscaleField, value) != true)) {
                    this.CodiceFiscaleField = value;
                    this.RaisePropertyChanged("CodiceFiscale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailEcommerce {
            get {
                return this.EmailEcommerceField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailEcommerceField, value) != true)) {
                    this.EmailEcommerceField = value;
                    this.RaisePropertyChanged("EmailEcommerce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HiddenPricePassword {
            get {
                return this.HiddenPricePasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.HiddenPricePasswordField, value) != true)) {
                    this.HiddenPricePasswordField = value;
                    this.RaisePropertyChanged("HiddenPricePassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Indirizzo {
            get {
                return this.IndirizzoField;
            }
            set {
                if ((object.ReferenceEquals(this.IndirizzoField, value) != true)) {
                    this.IndirizzoField = value;
                    this.RaisePropertyChanged("Indirizzo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsHiddenPrice {
            get {
                return this.IsHiddenPriceField;
            }
            set {
                if ((this.IsHiddenPriceField.Equals(value) != true)) {
                    this.IsHiddenPriceField = value;
                    this.RaisePropertyChanged("IsHiddenPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazione {
            get {
                return this.NazioneField;
            }
            set {
                if ((object.ReferenceEquals(this.NazioneField, value) != true)) {
                    this.NazioneField = value;
                    this.RaisePropertyChanged("Nazione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitaIva {
            get {
                return this.PartitaIvaField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitaIvaField, value) != true)) {
                    this.PartitaIvaField = value;
                    this.RaisePropertyChanged("PartitaIva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RagioneSociale {
            get {
                return this.RagioneSocialeField;
            }
            set {
                if ((object.ReferenceEquals(this.RagioneSocialeField, value) != true)) {
                    this.RagioneSocialeField = value;
                    this.RaisePropertyChanged("RagioneSociale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipologia {
            get {
                return this.TipologiaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipologiaField, value) != true)) {
                    this.TipologiaField = value;
                    this.RaisePropertyChanged("Tipologia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IndirizzoSpedizione", Namespace="http://schemas.datacontract.org/2004/07/NAVB2BService.Classi")]
    [System.SerializableAttribute()]
    public partial class IndirizzoSpedizione : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CAPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CittaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> DefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndirizzoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CAP {
            get {
                return this.CAPField;
            }
            set {
                if ((object.ReferenceEquals(this.CAPField, value) != true)) {
                    this.CAPField = value;
                    this.RaisePropertyChanged("CAP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Citta {
            get {
                return this.CittaField;
            }
            set {
                if ((object.ReferenceEquals(this.CittaField, value) != true)) {
                    this.CittaField = value;
                    this.RaisePropertyChanged("Citta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codice {
            get {
                return this.CodiceField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceField, value) != true)) {
                    this.CodiceField = value;
                    this.RaisePropertyChanged("Codice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceCliente {
            get {
                return this.CodiceClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceClienteField, value) != true)) {
                    this.CodiceClienteField = value;
                    this.RaisePropertyChanged("CodiceCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Default {
            get {
                return this.DefaultField;
            }
            set {
                if ((this.DefaultField.Equals(value) != true)) {
                    this.DefaultField = value;
                    this.RaisePropertyChanged("Default");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Indirizzo {
            get {
                return this.IndirizzoField;
            }
            set {
                if ((object.ReferenceEquals(this.IndirizzoField, value) != true)) {
                    this.IndirizzoField = value;
                    this.RaisePropertyChanged("Indirizzo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazione {
            get {
                return this.NazioneField;
            }
            set {
                if ((object.ReferenceEquals(this.NazioneField, value) != true)) {
                    this.NazioneField = value;
                    this.RaisePropertyChanged("Nazione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrezzoArticolo", Namespace="http://schemas.datacontract.org/2004/07/NAVB2BService.Classi")]
    [System.SerializableAttribute()]
    public partial class PrezzoArticolo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceArticoloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrezzoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ScontoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceArticolo {
            get {
                return this.CodiceArticoloField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceArticoloField, value) != true)) {
                    this.CodiceArticoloField = value;
                    this.RaisePropertyChanged("CodiceArticolo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Prezzo {
            get {
                return this.PrezzoField;
            }
            set {
                if ((this.PrezzoField.Equals(value) != true)) {
                    this.PrezzoField = value;
                    this.RaisePropertyChanged("Prezzo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Sconto {
            get {
                return this.ScontoField;
            }
            set {
                if ((this.ScontoField.Equals(value) != true)) {
                    this.ScontoField = value;
                    this.RaisePropertyChanged("Sconto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ordine", Namespace="http://schemas.datacontract.org/2004/07/NAVB2BService.Classi")]
    [System.SerializableAttribute()]
    public partial class Ordine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceArticoloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceIndirizzoDestinazioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataOrdineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NrOrdineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NrRigaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal QuantitaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceArticolo {
            get {
                return this.CodiceArticoloField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceArticoloField, value) != true)) {
                    this.CodiceArticoloField = value;
                    this.RaisePropertyChanged("CodiceArticolo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceCliente {
            get {
                return this.CodiceClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceClienteField, value) != true)) {
                    this.CodiceClienteField = value;
                    this.RaisePropertyChanged("CodiceCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceIndirizzoDestinazione {
            get {
                return this.CodiceIndirizzoDestinazioneField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceIndirizzoDestinazioneField, value) != true)) {
                    this.CodiceIndirizzoDestinazioneField = value;
                    this.RaisePropertyChanged("CodiceIndirizzoDestinazione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataOrdine {
            get {
                return this.DataOrdineField;
            }
            set {
                if ((this.DataOrdineField.Equals(value) != true)) {
                    this.DataOrdineField = value;
                    this.RaisePropertyChanged("DataOrdine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NrOrdine {
            get {
                return this.NrOrdineField;
            }
            set {
                if ((object.ReferenceEquals(this.NrOrdineField, value) != true)) {
                    this.NrOrdineField = value;
                    this.RaisePropertyChanged("NrOrdine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NrRiga {
            get {
                return this.NrRigaField;
            }
            set {
                if ((this.NrRigaField.Equals(value) != true)) {
                    this.NrRigaField = value;
                    this.RaisePropertyChanged("NrRiga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Quantita {
            get {
                return this.QuantitaField;
            }
            set {
                if ((this.QuantitaField.Equals(value) != true)) {
                    this.QuantitaField = value;
                    this.RaisePropertyChanged("Quantita");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="B2BPassword", Namespace="http://schemas.datacontract.org/2004/07/NAVB2BService.Classi")]
    [System.SerializableAttribute()]
    public partial class B2BPassword : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MD5HiddenPricePasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MD5PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UtenteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MD5HiddenPricePassword {
            get {
                return this.MD5HiddenPricePasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.MD5HiddenPricePasswordField, value) != true)) {
                    this.MD5HiddenPricePasswordField = value;
                    this.RaisePropertyChanged("MD5HiddenPricePassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MD5Password {
            get {
                return this.MD5PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.MD5PasswordField, value) != true)) {
                    this.MD5PasswordField = value;
                    this.RaisePropertyChanged("MD5Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Utente {
            get {
                return this.UtenteField;
            }
            set {
                if ((object.ReferenceEquals(this.UtenteField, value) != true)) {
                    this.UtenteField = value;
                    this.RaisePropertyChanged("Utente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="B2B.IB2BService")]
    public interface IB2BService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IB2BService/GetArticoliXML", ReplyAction="http://tempuri.org/IB2BService/GetArticoliXMLResponse")]
        TESTApp.B2B.Articolo[] GetArticoliXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IB2BService/GetArticoliJSON", ReplyAction="http://tempuri.org/IB2BService/GetArticoliJSONResponse")]
        TESTApp.B2B.Articolo[] GetArticoliJSON();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IB2BService/GetArticoliXMLbyDate", ReplyAction="http://tempuri.org/IB2BService/GetArticoliXMLbyDateResponse")]
        TESTApp.B2B.Articolo[] GetArticoliXMLbyDate(string DataModifica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IB2BService/GetArticoliJSONbyDate", ReplyAction="http://tempuri.org/IB2BService/GetArticoliJSONbyDateResponse")]
        TESTApp.B2B.Articolo[] GetArticoliJSONbyDate(string DataModifica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IB2BService/GetClientiXML", ReplyAction="http://tempuri.org/IB2BService/GetClientiXMLResponse")]
        TESTApp.B2B.Cliente[] GetClientiXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IB2BService/GetClientiJSON", ReplyAction="http://tempuri.org/IB2BService/GetClientiJSONResponse")]
        TESTApp.B2B.Cliente[] GetClientiJSON();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IB2BService/GetIndirizziSpedizioneClientiXML", ReplyAction="http://tempuri.org/IB2BService/GetIndirizziSpedizioneClientiXMLResponse")]
        TESTApp.B2B.IndirizzoSpedizione[] GetIndirizziSpedizioneClientiXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IB2BService/GetIndirizziSpedizioneClientiJSON", ReplyAction="http://tempuri.org/IB2BService/GetIndirizziSpedizioneClientiJSONResponse")]
        TESTApp.B2B.IndirizzoSpedizione[] GetIndirizziSpedizioneClientiJSON();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IB2BService/GetPrezzoVenditaXML", ReplyAction="http://tempuri.org/IB2BService/GetPrezzoVenditaXMLResponse")]
        decimal GetPrezzoVenditaXML(string CodiceCliente, string DataOrdine, string NrArticolo, decimal Quantita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IB2BService/GetPrezzoVenditaJSON", ReplyAction="http://tempuri.org/IB2BService/GetPrezzoVenditaJSONResponse")]
        decimal GetPrezzoVenditaJSON(string CodiceCliente, string DataOrdine, string NrArticolo, decimal Quantita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IB2BService/GetScontoVenditaXML", ReplyAction="http://tempuri.org/IB2BService/GetScontoVenditaXMLResponse")]
        decimal GetScontoVenditaXML(string CodiceCliente, string DataOrdine, string NrArticolo, decimal Quantita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IB2BService/GetScontoVenditaJSON", ReplyAction="http://tempuri.org/IB2BService/GetScontoVenditaJSONResponse")]
        decimal GetScontoVenditaJSON(string CodiceCliente, string DataOrdine, string NrArticolo, decimal Quantita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IB2BService/GetPrezzoArticoloXML", ReplyAction="http://tempuri.org/IB2BService/GetPrezzoArticoloXMLResponse")]
        TESTApp.B2B.PrezzoArticolo GetPrezzoArticoloXML(string CodiceCliente, string DataOrdine, string NrArticolo, decimal Quantita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IB2BService/GetPrezzoArticoloJSON", ReplyAction="http://tempuri.org/IB2BService/GetPrezzoArticoloJSONResponse")]
        TESTApp.B2B.PrezzoArticolo GetPrezzoArticoloJSON(string CodiceCliente, string DataOrdine, string NrArticolo, decimal Quantita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IB2BService/InsertOrderXML", ReplyAction="http://tempuri.org/IB2BService/InsertOrderXMLResponse")]
        string InsertOrderXML(TESTApp.B2B.Ordine ordine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IB2BService/InsertOrderJSON", ReplyAction="http://tempuri.org/IB2BService/InsertOrderJSONResponse")]
        string InsertOrderJSON(TESTApp.B2B.Ordine ordine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IB2BService/UpdateB2BPasswordXML", ReplyAction="http://tempuri.org/IB2BService/UpdateB2BPasswordXMLResponse")]
        string UpdateB2BPasswordXML(TESTApp.B2B.B2BPassword password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IB2BService/UpdateB2BPasswordJSON", ReplyAction="http://tempuri.org/IB2BService/UpdateB2BPasswordJSONResponse")]
        string UpdateB2BPasswordJSON(TESTApp.B2B.B2BPassword password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IB2BServiceChannel : TESTApp.B2B.IB2BService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class B2BServiceClient : System.ServiceModel.ClientBase<TESTApp.B2B.IB2BService>, TESTApp.B2B.IB2BService {
        
        public B2BServiceClient() {
        }
        
        public B2BServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public B2BServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public B2BServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public B2BServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TESTApp.B2B.Articolo[] GetArticoliXML() {
            return base.Channel.GetArticoliXML();
        }
        
        public TESTApp.B2B.Articolo[] GetArticoliJSON() {
            return base.Channel.GetArticoliJSON();
        }
        
        public TESTApp.B2B.Articolo[] GetArticoliXMLbyDate(string DataModifica) {
            return base.Channel.GetArticoliXMLbyDate(DataModifica);
        }
        
        public TESTApp.B2B.Articolo[] GetArticoliJSONbyDate(string DataModifica) {
            return base.Channel.GetArticoliJSONbyDate(DataModifica);
        }
        
        public TESTApp.B2B.Cliente[] GetClientiXML() {
            return base.Channel.GetClientiXML();
        }
        
        public TESTApp.B2B.Cliente[] GetClientiJSON() {
            return base.Channel.GetClientiJSON();
        }
        
        public TESTApp.B2B.IndirizzoSpedizione[] GetIndirizziSpedizioneClientiXML() {
            return base.Channel.GetIndirizziSpedizioneClientiXML();
        }
        
        public TESTApp.B2B.IndirizzoSpedizione[] GetIndirizziSpedizioneClientiJSON() {
            return base.Channel.GetIndirizziSpedizioneClientiJSON();
        }
        
        public decimal GetPrezzoVenditaXML(string CodiceCliente, string DataOrdine, string NrArticolo, decimal Quantita) {
            return base.Channel.GetPrezzoVenditaXML(CodiceCliente, DataOrdine, NrArticolo, Quantita);
        }
        
        public decimal GetPrezzoVenditaJSON(string CodiceCliente, string DataOrdine, string NrArticolo, decimal Quantita) {
            return base.Channel.GetPrezzoVenditaJSON(CodiceCliente, DataOrdine, NrArticolo, Quantita);
        }
        
        public decimal GetScontoVenditaXML(string CodiceCliente, string DataOrdine, string NrArticolo, decimal Quantita) {
            return base.Channel.GetScontoVenditaXML(CodiceCliente, DataOrdine, NrArticolo, Quantita);
        }
        
        public decimal GetScontoVenditaJSON(string CodiceCliente, string DataOrdine, string NrArticolo, decimal Quantita) {
            return base.Channel.GetScontoVenditaJSON(CodiceCliente, DataOrdine, NrArticolo, Quantita);
        }
        
        public TESTApp.B2B.PrezzoArticolo GetPrezzoArticoloXML(string CodiceCliente, string DataOrdine, string NrArticolo, decimal Quantita) {
            return base.Channel.GetPrezzoArticoloXML(CodiceCliente, DataOrdine, NrArticolo, Quantita);
        }
        
        public TESTApp.B2B.PrezzoArticolo GetPrezzoArticoloJSON(string CodiceCliente, string DataOrdine, string NrArticolo, decimal Quantita) {
            return base.Channel.GetPrezzoArticoloJSON(CodiceCliente, DataOrdine, NrArticolo, Quantita);
        }
        
        public string InsertOrderXML(TESTApp.B2B.Ordine ordine) {
            return base.Channel.InsertOrderXML(ordine);
        }
        
        public string InsertOrderJSON(TESTApp.B2B.Ordine ordine) {
            return base.Channel.InsertOrderJSON(ordine);
        }
        
        public string UpdateB2BPasswordXML(TESTApp.B2B.B2BPassword password) {
            return base.Channel.UpdateB2BPasswordXML(password);
        }
        
        public string UpdateB2BPasswordJSON(TESTApp.B2B.B2BPassword password) {
            return base.Channel.UpdateB2BPasswordJSON(password);
        }
    }
}
