//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ConsoleApplicationNAV.NAVWS_SalesLines {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SalesOrderLInes_Binding", Namespace="urn:microsoft-dynamics-schemas/page/salesorderlines")]
    public partial class SalesOrderLInes_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SalesOrderLInes_Service() {
            this.Url = global::ConsoleApplicationNAV.Properties.Settings.Default.ConsoleApplicationNAV_NAVWS_SalesLines_SalesOrderLInes_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event CreateMultipleCompletedEventHandler CreateMultipleCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/salesorderlines:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/salesorderlines", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/salesorderlines", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SalesOrderLInes")]
        public SalesOrderLInes Read(string Document_No, int Line_No) {
            object[] results = this.Invoke("Read", new object[] {
                        Document_No,
                        Line_No});
            return ((SalesOrderLInes)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(string Document_No, int Line_No) {
            this.ReadAsync(Document_No, Line_No, null);
        }
        
        /// <remarks/>
        public void ReadAsync(string Document_No, int Line_No, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        Document_No,
                        Line_No}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/salesorderlines:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/salesorderlines", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/salesorderlines", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SalesOrderLInes")]
        public SalesOrderLInes ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((SalesOrderLInes)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/salesorderlines:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/salesorderlines", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/salesorderlines", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SalesOrderLInes[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] SalesOrderLInes_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((SalesOrderLInes[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(SalesOrderLInes_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(SalesOrderLInes_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/salesorderlines:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/salesorderlines", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/salesorderlines", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/salesorderlines:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/salesorderlines", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/salesorderlines", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/salesorderlines:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/salesorderlines", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/salesorderlines", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref SalesOrderLInes SalesOrderLInes) {
            object[] results = this.Invoke("Create", new object[] {
                        SalesOrderLInes});
            SalesOrderLInes = ((SalesOrderLInes)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(SalesOrderLInes SalesOrderLInes) {
            this.CreateAsync(SalesOrderLInes, null);
        }
        
        /// <remarks/>
        public void CreateAsync(SalesOrderLInes SalesOrderLInes, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        SalesOrderLInes}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/salesorderlines:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/salesorderlines", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/salesorderlines", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref SalesOrderLInes[] SalesOrderLInes_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        SalesOrderLInes_List});
            SalesOrderLInes_List = ((SalesOrderLInes[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(SalesOrderLInes[] SalesOrderLInes_List) {
            this.CreateMultipleAsync(SalesOrderLInes_List, null);
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(SalesOrderLInes[] SalesOrderLInes_List, object userState) {
            if ((this.CreateMultipleOperationCompleted == null)) {
                this.CreateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultipleOperationCompleted);
            }
            this.InvokeAsync("CreateMultiple", new object[] {
                        SalesOrderLInes_List}, this.CreateMultipleOperationCompleted, userState);
        }
        
        private void OnCreateMultipleOperationCompleted(object arg) {
            if ((this.CreateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultipleCompleted(this, new CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/salesorderlines:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/salesorderlines", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/salesorderlines", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref SalesOrderLInes SalesOrderLInes) {
            object[] results = this.Invoke("Update", new object[] {
                        SalesOrderLInes});
            SalesOrderLInes = ((SalesOrderLInes)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(SalesOrderLInes SalesOrderLInes) {
            this.UpdateAsync(SalesOrderLInes, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(SalesOrderLInes SalesOrderLInes, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        SalesOrderLInes}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/salesorderlines:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/salesorderlines", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/salesorderlines", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref SalesOrderLInes[] SalesOrderLInes_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        SalesOrderLInes_List});
            SalesOrderLInes_List = ((SalesOrderLInes[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(SalesOrderLInes[] SalesOrderLInes_List) {
            this.UpdateMultipleAsync(SalesOrderLInes_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(SalesOrderLInes[] SalesOrderLInes_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        SalesOrderLInes_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/salesorderlines:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/salesorderlines", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/salesorderlines", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key) {
            this.DeleteAsync(Key, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        Key}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salesorderlines")]
    public partial class SalesOrderLInes {
        
        private string keyField;
        
        private Type typeField;
        
        private bool typeFieldSpecified;
        
        private string noField;
        
        private string service_Tariff_NoField;
        
        private string cross_Reference_NoField;
        
        private bool include_in_VAT_Transac_RepField;
        
        private bool include_in_VAT_Transac_RepFieldSpecified;
        
        private string iC_Partner_CodeField;
        
        private IC_Partner_Ref_Type iC_Partner_Ref_TypeField;
        
        private bool iC_Partner_Ref_TypeFieldSpecified;
        
        private Prepmt_CM_Refers_to_Period prepmt_CM_Refers_to_PeriodField;
        
        private bool prepmt_CM_Refers_to_PeriodFieldSpecified;
        
        private string iC_Partner_ReferenceField;
        
        private string variant_CodeField;
        
        private bool substitution_AvailableField;
        
        private bool substitution_AvailableFieldSpecified;
        
        private string purchasing_CodeField;
        
        private bool nonstockField;
        
        private bool nonstockFieldSpecified;
        
        private string vAT_Prod_Posting_GroupField;
        
        private string descriptionField;
        
        private bool drop_ShipmentField;
        
        private bool drop_ShipmentFieldSpecified;
        
        private bool special_OrderField;
        
        private bool special_OrderFieldSpecified;
        
        private string return_Reason_CodeField;
        
        private string location_CodeField;
        
        private string bin_CodeField;
        
        private Reserve reserveField;
        
        private bool reserveFieldSpecified;
        
        private decimal quantityField;
        
        private bool quantityFieldSpecified;
        
        private decimal qty_to_Assemble_to_OrderField;
        
        private bool qty_to_Assemble_to_OrderFieldSpecified;
        
        private decimal reserved_QuantityField;
        
        private bool reserved_QuantityFieldSpecified;
        
        private string unit_of_Measure_CodeField;
        
        private string unit_of_MeasureField;
        
        private decimal unit_Cost_LCYField;
        
        private bool unit_Cost_LCYFieldSpecified;
        
        private bool salesPriceExistField;
        
        private bool salesPriceExistFieldSpecified;
        
        private decimal unit_PriceField;
        
        private bool unit_PriceFieldSpecified;
        
        private decimal line_AmountField;
        
        private bool line_AmountFieldSpecified;
        
        private bool salesLineDiscExistsField;
        
        private bool salesLineDiscExistsFieldSpecified;
        
        private decimal line_Discount_PercentField;
        
        private bool line_Discount_PercentFieldSpecified;
        
        private decimal line_Discount_AmountField;
        
        private bool line_Discount_AmountFieldSpecified;
        
        private decimal prepayment_PercentField;
        
        private bool prepayment_PercentFieldSpecified;
        
        private decimal prepmt_Line_AmountField;
        
        private bool prepmt_Line_AmountFieldSpecified;
        
        private decimal prepmt_Amt_InvField;
        
        private bool prepmt_Amt_InvFieldSpecified;
        
        private bool allow_Invoice_DiscField;
        
        private bool allow_Invoice_DiscFieldSpecified;
        
        private decimal inv_Discount_AmountField;
        
        private bool inv_Discount_AmountFieldSpecified;
        
        private decimal qty_to_ShipField;
        
        private bool qty_to_ShipFieldSpecified;
        
        private decimal quantity_ShippedField;
        
        private bool quantity_ShippedFieldSpecified;
        
        private decimal qty_to_InvoiceField;
        
        private bool qty_to_InvoiceFieldSpecified;
        
        private decimal quantity_InvoicedField;
        
        private bool quantity_InvoicedFieldSpecified;
        
        private decimal prepmt_Amt_to_DeductField;
        
        private bool prepmt_Amt_to_DeductFieldSpecified;
        
        private decimal prepmt_Amt_DeductedField;
        
        private bool prepmt_Amt_DeductedFieldSpecified;
        
        private bool allow_Item_Charge_AssignmentField;
        
        private bool allow_Item_Charge_AssignmentFieldSpecified;
        
        private decimal qty_to_AssignField;
        
        private bool qty_to_AssignFieldSpecified;
        
        private decimal qty_AssignedField;
        
        private bool qty_AssignedFieldSpecified;
        
        private System.DateTime requested_Delivery_DateField;
        
        private bool requested_Delivery_DateFieldSpecified;
        
        private System.DateTime promised_Delivery_DateField;
        
        private bool promised_Delivery_DateFieldSpecified;
        
        private System.DateTime planned_Delivery_DateField;
        
        private bool planned_Delivery_DateFieldSpecified;
        
        private System.DateTime planned_Shipment_DateField;
        
        private bool planned_Shipment_DateFieldSpecified;
        
        private System.DateTime shipment_DateField;
        
        private bool shipment_DateFieldSpecified;
        
        private string shipping_Agent_CodeField;
        
        private string shipping_Agent_Service_CodeField;
        
        private string shipping_TimeField;
        
        private string work_Type_CodeField;
        
        private decimal whse_Outstanding_QtyField;
        
        private bool whse_Outstanding_QtyFieldSpecified;
        
        private decimal whse_Outstanding_Qty_BaseField;
        
        private bool whse_Outstanding_Qty_BaseFieldSpecified;
        
        private decimal aTO_Whse_Outstanding_QtyField;
        
        private bool aTO_Whse_Outstanding_QtyFieldSpecified;
        
        private decimal aTO_Whse_Outstd_Qty_BaseField;
        
        private bool aTO_Whse_Outstd_Qty_BaseFieldSpecified;
        
        private string outbound_Whse_Handling_TimeField;
        
        private string blanket_Order_NoField;
        
        private int blanket_Order_Line_NoField;
        
        private bool blanket_Order_Line_NoFieldSpecified;
        
        private System.DateTime fA_Posting_DateField;
        
        private bool fA_Posting_DateFieldSpecified;
        
        private bool depr_until_FA_Posting_DateField;
        
        private bool depr_until_FA_Posting_DateFieldSpecified;
        
        private string depreciation_Book_CodeField;
        
        private bool use_Duplication_ListField;
        
        private bool use_Duplication_ListFieldSpecified;
        
        private string duplicate_in_Depreciation_BookField;
        
        private int appl_from_Item_EntryField;
        
        private bool appl_from_Item_EntryFieldSpecified;
        
        private int appl_to_Item_EntryField;
        
        private bool appl_to_Item_EntryFieldSpecified;
        
        private string deferral_CodeField;
        
        private string shortcut_Dimension_1_CodeField;
        
        private string shortcut_Dimension_2_CodeField;
        
        private string shortcutDimCode3Field;
        
        private string shortcutDimCode4Field;
        
        private string shortcutDimCode5Field;
        
        private string shortcutDimCode6Field;
        
        private string shortcutDimCode7Field;
        
        private string shortcutDimCode8Field;
        
        private string document_NoField;
        
        private int line_NoField;
        
        private bool line_NoFieldSpecified;
        
        private decimal invoice_Discount_AmountField;
        
        private bool invoice_Discount_AmountFieldSpecified;
        
        private decimal invoice_Disc_PctField;
        
        private bool invoice_Disc_PctFieldSpecified;
        
        private decimal total_Amount_Excl_VATField;
        
        private bool total_Amount_Excl_VATFieldSpecified;
        
        private decimal total_VAT_AmountField;
        
        private bool total_VAT_AmountFieldSpecified;
        
        private decimal total_Amount_Incl_VATField;
        
        private bool total_Amount_Incl_VATFieldSpecified;
        
        private string refreshTotalsField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public Type Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string Service_Tariff_No {
            get {
                return this.service_Tariff_NoField;
            }
            set {
                this.service_Tariff_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Cross_Reference_No {
            get {
                return this.cross_Reference_NoField;
            }
            set {
                this.cross_Reference_NoField = value;
            }
        }
        
        /// <remarks/>
        public bool Include_in_VAT_Transac_Rep {
            get {
                return this.include_in_VAT_Transac_RepField;
            }
            set {
                this.include_in_VAT_Transac_RepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Include_in_VAT_Transac_RepSpecified {
            get {
                return this.include_in_VAT_Transac_RepFieldSpecified;
            }
            set {
                this.include_in_VAT_Transac_RepFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string IC_Partner_Code {
            get {
                return this.iC_Partner_CodeField;
            }
            set {
                this.iC_Partner_CodeField = value;
            }
        }
        
        /// <remarks/>
        public IC_Partner_Ref_Type IC_Partner_Ref_Type {
            get {
                return this.iC_Partner_Ref_TypeField;
            }
            set {
                this.iC_Partner_Ref_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IC_Partner_Ref_TypeSpecified {
            get {
                return this.iC_Partner_Ref_TypeFieldSpecified;
            }
            set {
                this.iC_Partner_Ref_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Prepmt_CM_Refers_to_Period Prepmt_CM_Refers_to_Period {
            get {
                return this.prepmt_CM_Refers_to_PeriodField;
            }
            set {
                this.prepmt_CM_Refers_to_PeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Prepmt_CM_Refers_to_PeriodSpecified {
            get {
                return this.prepmt_CM_Refers_to_PeriodFieldSpecified;
            }
            set {
                this.prepmt_CM_Refers_to_PeriodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string IC_Partner_Reference {
            get {
                return this.iC_Partner_ReferenceField;
            }
            set {
                this.iC_Partner_ReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string Variant_Code {
            get {
                return this.variant_CodeField;
            }
            set {
                this.variant_CodeField = value;
            }
        }
        
        /// <remarks/>
        public bool Substitution_Available {
            get {
                return this.substitution_AvailableField;
            }
            set {
                this.substitution_AvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Substitution_AvailableSpecified {
            get {
                return this.substitution_AvailableFieldSpecified;
            }
            set {
                this.substitution_AvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Purchasing_Code {
            get {
                return this.purchasing_CodeField;
            }
            set {
                this.purchasing_CodeField = value;
            }
        }
        
        /// <remarks/>
        public bool Nonstock {
            get {
                return this.nonstockField;
            }
            set {
                this.nonstockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NonstockSpecified {
            get {
                return this.nonstockFieldSpecified;
            }
            set {
                this.nonstockFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string VAT_Prod_Posting_Group {
            get {
                return this.vAT_Prod_Posting_GroupField;
            }
            set {
                this.vAT_Prod_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool Drop_Shipment {
            get {
                return this.drop_ShipmentField;
            }
            set {
                this.drop_ShipmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Drop_ShipmentSpecified {
            get {
                return this.drop_ShipmentFieldSpecified;
            }
            set {
                this.drop_ShipmentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Special_Order {
            get {
                return this.special_OrderField;
            }
            set {
                this.special_OrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Special_OrderSpecified {
            get {
                return this.special_OrderFieldSpecified;
            }
            set {
                this.special_OrderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Return_Reason_Code {
            get {
                return this.return_Reason_CodeField;
            }
            set {
                this.return_Reason_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Location_Code {
            get {
                return this.location_CodeField;
            }
            set {
                this.location_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Bin_Code {
            get {
                return this.bin_CodeField;
            }
            set {
                this.bin_CodeField = value;
            }
        }
        
        /// <remarks/>
        public Reserve Reserve {
            get {
                return this.reserveField;
            }
            set {
                this.reserveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReserveSpecified {
            get {
                return this.reserveFieldSpecified;
            }
            set {
                this.reserveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty_to_Assemble_to_Order {
            get {
                return this.qty_to_Assemble_to_OrderField;
            }
            set {
                this.qty_to_Assemble_to_OrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_to_Assemble_to_OrderSpecified {
            get {
                return this.qty_to_Assemble_to_OrderFieldSpecified;
            }
            set {
                this.qty_to_Assemble_to_OrderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Reserved_Quantity {
            get {
                return this.reserved_QuantityField;
            }
            set {
                this.reserved_QuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Reserved_QuantitySpecified {
            get {
                return this.reserved_QuantityFieldSpecified;
            }
            set {
                this.reserved_QuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Unit_of_Measure_Code {
            get {
                return this.unit_of_Measure_CodeField;
            }
            set {
                this.unit_of_Measure_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Unit_of_Measure {
            get {
                return this.unit_of_MeasureField;
            }
            set {
                this.unit_of_MeasureField = value;
            }
        }
        
        /// <remarks/>
        public decimal Unit_Cost_LCY {
            get {
                return this.unit_Cost_LCYField;
            }
            set {
                this.unit_Cost_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Unit_Cost_LCYSpecified {
            get {
                return this.unit_Cost_LCYFieldSpecified;
            }
            set {
                this.unit_Cost_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool SalesPriceExist {
            get {
                return this.salesPriceExistField;
            }
            set {
                this.salesPriceExistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalesPriceExistSpecified {
            get {
                return this.salesPriceExistFieldSpecified;
            }
            set {
                this.salesPriceExistFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Unit_Price {
            get {
                return this.unit_PriceField;
            }
            set {
                this.unit_PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Unit_PriceSpecified {
            get {
                return this.unit_PriceFieldSpecified;
            }
            set {
                this.unit_PriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Line_Amount {
            get {
                return this.line_AmountField;
            }
            set {
                this.line_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Line_AmountSpecified {
            get {
                return this.line_AmountFieldSpecified;
            }
            set {
                this.line_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool SalesLineDiscExists {
            get {
                return this.salesLineDiscExistsField;
            }
            set {
                this.salesLineDiscExistsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalesLineDiscExistsSpecified {
            get {
                return this.salesLineDiscExistsFieldSpecified;
            }
            set {
                this.salesLineDiscExistsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Line_Discount_Percent {
            get {
                return this.line_Discount_PercentField;
            }
            set {
                this.line_Discount_PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Line_Discount_PercentSpecified {
            get {
                return this.line_Discount_PercentFieldSpecified;
            }
            set {
                this.line_Discount_PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Line_Discount_Amount {
            get {
                return this.line_Discount_AmountField;
            }
            set {
                this.line_Discount_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Line_Discount_AmountSpecified {
            get {
                return this.line_Discount_AmountFieldSpecified;
            }
            set {
                this.line_Discount_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Prepayment_Percent {
            get {
                return this.prepayment_PercentField;
            }
            set {
                this.prepayment_PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Prepayment_PercentSpecified {
            get {
                return this.prepayment_PercentFieldSpecified;
            }
            set {
                this.prepayment_PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Prepmt_Line_Amount {
            get {
                return this.prepmt_Line_AmountField;
            }
            set {
                this.prepmt_Line_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Prepmt_Line_AmountSpecified {
            get {
                return this.prepmt_Line_AmountFieldSpecified;
            }
            set {
                this.prepmt_Line_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Prepmt_Amt_Inv {
            get {
                return this.prepmt_Amt_InvField;
            }
            set {
                this.prepmt_Amt_InvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Prepmt_Amt_InvSpecified {
            get {
                return this.prepmt_Amt_InvFieldSpecified;
            }
            set {
                this.prepmt_Amt_InvFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Allow_Invoice_Disc {
            get {
                return this.allow_Invoice_DiscField;
            }
            set {
                this.allow_Invoice_DiscField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Allow_Invoice_DiscSpecified {
            get {
                return this.allow_Invoice_DiscFieldSpecified;
            }
            set {
                this.allow_Invoice_DiscFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Inv_Discount_Amount {
            get {
                return this.inv_Discount_AmountField;
            }
            set {
                this.inv_Discount_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Inv_Discount_AmountSpecified {
            get {
                return this.inv_Discount_AmountFieldSpecified;
            }
            set {
                this.inv_Discount_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty_to_Ship {
            get {
                return this.qty_to_ShipField;
            }
            set {
                this.qty_to_ShipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_to_ShipSpecified {
            get {
                return this.qty_to_ShipFieldSpecified;
            }
            set {
                this.qty_to_ShipFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity_Shipped {
            get {
                return this.quantity_ShippedField;
            }
            set {
                this.quantity_ShippedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Quantity_ShippedSpecified {
            get {
                return this.quantity_ShippedFieldSpecified;
            }
            set {
                this.quantity_ShippedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty_to_Invoice {
            get {
                return this.qty_to_InvoiceField;
            }
            set {
                this.qty_to_InvoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_to_InvoiceSpecified {
            get {
                return this.qty_to_InvoiceFieldSpecified;
            }
            set {
                this.qty_to_InvoiceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity_Invoiced {
            get {
                return this.quantity_InvoicedField;
            }
            set {
                this.quantity_InvoicedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Quantity_InvoicedSpecified {
            get {
                return this.quantity_InvoicedFieldSpecified;
            }
            set {
                this.quantity_InvoicedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Prepmt_Amt_to_Deduct {
            get {
                return this.prepmt_Amt_to_DeductField;
            }
            set {
                this.prepmt_Amt_to_DeductField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Prepmt_Amt_to_DeductSpecified {
            get {
                return this.prepmt_Amt_to_DeductFieldSpecified;
            }
            set {
                this.prepmt_Amt_to_DeductFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Prepmt_Amt_Deducted {
            get {
                return this.prepmt_Amt_DeductedField;
            }
            set {
                this.prepmt_Amt_DeductedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Prepmt_Amt_DeductedSpecified {
            get {
                return this.prepmt_Amt_DeductedFieldSpecified;
            }
            set {
                this.prepmt_Amt_DeductedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Allow_Item_Charge_Assignment {
            get {
                return this.allow_Item_Charge_AssignmentField;
            }
            set {
                this.allow_Item_Charge_AssignmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Allow_Item_Charge_AssignmentSpecified {
            get {
                return this.allow_Item_Charge_AssignmentFieldSpecified;
            }
            set {
                this.allow_Item_Charge_AssignmentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty_to_Assign {
            get {
                return this.qty_to_AssignField;
            }
            set {
                this.qty_to_AssignField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_to_AssignSpecified {
            get {
                return this.qty_to_AssignFieldSpecified;
            }
            set {
                this.qty_to_AssignFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty_Assigned {
            get {
                return this.qty_AssignedField;
            }
            set {
                this.qty_AssignedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_AssignedSpecified {
            get {
                return this.qty_AssignedFieldSpecified;
            }
            set {
                this.qty_AssignedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Requested_Delivery_Date {
            get {
                return this.requested_Delivery_DateField;
            }
            set {
                this.requested_Delivery_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Requested_Delivery_DateSpecified {
            get {
                return this.requested_Delivery_DateFieldSpecified;
            }
            set {
                this.requested_Delivery_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Promised_Delivery_Date {
            get {
                return this.promised_Delivery_DateField;
            }
            set {
                this.promised_Delivery_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Promised_Delivery_DateSpecified {
            get {
                return this.promised_Delivery_DateFieldSpecified;
            }
            set {
                this.promised_Delivery_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Planned_Delivery_Date {
            get {
                return this.planned_Delivery_DateField;
            }
            set {
                this.planned_Delivery_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Planned_Delivery_DateSpecified {
            get {
                return this.planned_Delivery_DateFieldSpecified;
            }
            set {
                this.planned_Delivery_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Planned_Shipment_Date {
            get {
                return this.planned_Shipment_DateField;
            }
            set {
                this.planned_Shipment_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Planned_Shipment_DateSpecified {
            get {
                return this.planned_Shipment_DateFieldSpecified;
            }
            set {
                this.planned_Shipment_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Shipment_Date {
            get {
                return this.shipment_DateField;
            }
            set {
                this.shipment_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Shipment_DateSpecified {
            get {
                return this.shipment_DateFieldSpecified;
            }
            set {
                this.shipment_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Shipping_Agent_Code {
            get {
                return this.shipping_Agent_CodeField;
            }
            set {
                this.shipping_Agent_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shipping_Agent_Service_Code {
            get {
                return this.shipping_Agent_Service_CodeField;
            }
            set {
                this.shipping_Agent_Service_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shipping_Time {
            get {
                return this.shipping_TimeField;
            }
            set {
                this.shipping_TimeField = value;
            }
        }
        
        /// <remarks/>
        public string Work_Type_Code {
            get {
                return this.work_Type_CodeField;
            }
            set {
                this.work_Type_CodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Whse_Outstanding_Qty {
            get {
                return this.whse_Outstanding_QtyField;
            }
            set {
                this.whse_Outstanding_QtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Whse_Outstanding_QtySpecified {
            get {
                return this.whse_Outstanding_QtyFieldSpecified;
            }
            set {
                this.whse_Outstanding_QtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Whse_Outstanding_Qty_Base {
            get {
                return this.whse_Outstanding_Qty_BaseField;
            }
            set {
                this.whse_Outstanding_Qty_BaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Whse_Outstanding_Qty_BaseSpecified {
            get {
                return this.whse_Outstanding_Qty_BaseFieldSpecified;
            }
            set {
                this.whse_Outstanding_Qty_BaseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal ATO_Whse_Outstanding_Qty {
            get {
                return this.aTO_Whse_Outstanding_QtyField;
            }
            set {
                this.aTO_Whse_Outstanding_QtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ATO_Whse_Outstanding_QtySpecified {
            get {
                return this.aTO_Whse_Outstanding_QtyFieldSpecified;
            }
            set {
                this.aTO_Whse_Outstanding_QtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal ATO_Whse_Outstd_Qty_Base {
            get {
                return this.aTO_Whse_Outstd_Qty_BaseField;
            }
            set {
                this.aTO_Whse_Outstd_Qty_BaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ATO_Whse_Outstd_Qty_BaseSpecified {
            get {
                return this.aTO_Whse_Outstd_Qty_BaseFieldSpecified;
            }
            set {
                this.aTO_Whse_Outstd_Qty_BaseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Outbound_Whse_Handling_Time {
            get {
                return this.outbound_Whse_Handling_TimeField;
            }
            set {
                this.outbound_Whse_Handling_TimeField = value;
            }
        }
        
        /// <remarks/>
        public string Blanket_Order_No {
            get {
                return this.blanket_Order_NoField;
            }
            set {
                this.blanket_Order_NoField = value;
            }
        }
        
        /// <remarks/>
        public int Blanket_Order_Line_No {
            get {
                return this.blanket_Order_Line_NoField;
            }
            set {
                this.blanket_Order_Line_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Blanket_Order_Line_NoSpecified {
            get {
                return this.blanket_Order_Line_NoFieldSpecified;
            }
            set {
                this.blanket_Order_Line_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime FA_Posting_Date {
            get {
                return this.fA_Posting_DateField;
            }
            set {
                this.fA_Posting_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FA_Posting_DateSpecified {
            get {
                return this.fA_Posting_DateFieldSpecified;
            }
            set {
                this.fA_Posting_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Depr_until_FA_Posting_Date {
            get {
                return this.depr_until_FA_Posting_DateField;
            }
            set {
                this.depr_until_FA_Posting_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Depr_until_FA_Posting_DateSpecified {
            get {
                return this.depr_until_FA_Posting_DateFieldSpecified;
            }
            set {
                this.depr_until_FA_Posting_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Depreciation_Book_Code {
            get {
                return this.depreciation_Book_CodeField;
            }
            set {
                this.depreciation_Book_CodeField = value;
            }
        }
        
        /// <remarks/>
        public bool Use_Duplication_List {
            get {
                return this.use_Duplication_ListField;
            }
            set {
                this.use_Duplication_ListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Use_Duplication_ListSpecified {
            get {
                return this.use_Duplication_ListFieldSpecified;
            }
            set {
                this.use_Duplication_ListFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Duplicate_in_Depreciation_Book {
            get {
                return this.duplicate_in_Depreciation_BookField;
            }
            set {
                this.duplicate_in_Depreciation_BookField = value;
            }
        }
        
        /// <remarks/>
        public int Appl_from_Item_Entry {
            get {
                return this.appl_from_Item_EntryField;
            }
            set {
                this.appl_from_Item_EntryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Appl_from_Item_EntrySpecified {
            get {
                return this.appl_from_Item_EntryFieldSpecified;
            }
            set {
                this.appl_from_Item_EntryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Appl_to_Item_Entry {
            get {
                return this.appl_to_Item_EntryField;
            }
            set {
                this.appl_to_Item_EntryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Appl_to_Item_EntrySpecified {
            get {
                return this.appl_to_Item_EntryFieldSpecified;
            }
            set {
                this.appl_to_Item_EntryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Deferral_Code {
            get {
                return this.deferral_CodeField;
            }
            set {
                this.deferral_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shortcut_Dimension_1_Code {
            get {
                return this.shortcut_Dimension_1_CodeField;
            }
            set {
                this.shortcut_Dimension_1_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shortcut_Dimension_2_Code {
            get {
                return this.shortcut_Dimension_2_CodeField;
            }
            set {
                this.shortcut_Dimension_2_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[3]")]
        public string ShortcutDimCode3 {
            get {
                return this.shortcutDimCode3Field;
            }
            set {
                this.shortcutDimCode3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[4]")]
        public string ShortcutDimCode4 {
            get {
                return this.shortcutDimCode4Field;
            }
            set {
                this.shortcutDimCode4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[5]")]
        public string ShortcutDimCode5 {
            get {
                return this.shortcutDimCode5Field;
            }
            set {
                this.shortcutDimCode5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[6]")]
        public string ShortcutDimCode6 {
            get {
                return this.shortcutDimCode6Field;
            }
            set {
                this.shortcutDimCode6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[7]")]
        public string ShortcutDimCode7 {
            get {
                return this.shortcutDimCode7Field;
            }
            set {
                this.shortcutDimCode7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[8]")]
        public string ShortcutDimCode8 {
            get {
                return this.shortcutDimCode8Field;
            }
            set {
                this.shortcutDimCode8Field = value;
            }
        }
        
        /// <remarks/>
        public string Document_No {
            get {
                return this.document_NoField;
            }
            set {
                this.document_NoField = value;
            }
        }
        
        /// <remarks/>
        public int Line_No {
            get {
                return this.line_NoField;
            }
            set {
                this.line_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Line_NoSpecified {
            get {
                return this.line_NoFieldSpecified;
            }
            set {
                this.line_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Invoice_Discount_Amount {
            get {
                return this.invoice_Discount_AmountField;
            }
            set {
                this.invoice_Discount_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Invoice_Discount_AmountSpecified {
            get {
                return this.invoice_Discount_AmountFieldSpecified;
            }
            set {
                this.invoice_Discount_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Invoice_Disc_Pct {
            get {
                return this.invoice_Disc_PctField;
            }
            set {
                this.invoice_Disc_PctField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Invoice_Disc_PctSpecified {
            get {
                return this.invoice_Disc_PctFieldSpecified;
            }
            set {
                this.invoice_Disc_PctFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Total_Amount_Excl_VAT {
            get {
                return this.total_Amount_Excl_VATField;
            }
            set {
                this.total_Amount_Excl_VATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Total_Amount_Excl_VATSpecified {
            get {
                return this.total_Amount_Excl_VATFieldSpecified;
            }
            set {
                this.total_Amount_Excl_VATFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Total_VAT_Amount {
            get {
                return this.total_VAT_AmountField;
            }
            set {
                this.total_VAT_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Total_VAT_AmountSpecified {
            get {
                return this.total_VAT_AmountFieldSpecified;
            }
            set {
                this.total_VAT_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Total_Amount_Incl_VAT {
            get {
                return this.total_Amount_Incl_VATField;
            }
            set {
                this.total_Amount_Incl_VATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Total_Amount_Incl_VATSpecified {
            get {
                return this.total_Amount_Incl_VATFieldSpecified;
            }
            set {
                this.total_Amount_Incl_VATFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string RefreshTotals {
            get {
                return this.refreshTotalsField;
            }
            set {
                this.refreshTotalsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salesorderlines")]
    public enum Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        G_L_Account,
        
        /// <remarks/>
        Item,
        
        /// <remarks/>
        Resource,
        
        /// <remarks/>
        Fixed_Asset,
        
        /// <remarks/>
        Charge_Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salesorderlines")]
    public enum IC_Partner_Ref_Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        G_L_Account,
        
        /// <remarks/>
        Item,
        
        /// <remarks/>
        Charge_Item,
        
        /// <remarks/>
        Cross_Reference,
        
        /// <remarks/>
        Common_Item_No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salesorderlines")]
    public enum Prepmt_CM_Refers_to_Period {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Current,
        
        /// <remarks/>
        Current_Calendar_Year,
        
        /// <remarks/>
        Previous_Calendar_Year,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salesorderlines")]
    public enum Reserve {
        
        /// <remarks/>
        Never,
        
        /// <remarks/>
        Optional,
        
        /// <remarks/>
        Always,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salesorderlines")]
    public partial class SalesOrderLInes_Filter {
        
        private SalesOrderLInes_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public SalesOrderLInes_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salesorderlines")]
    public enum SalesOrderLInes_Fields {
        
        /// <remarks/>
        Type,
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Service_Tariff_No,
        
        /// <remarks/>
        Cross_Reference_No,
        
        /// <remarks/>
        Include_in_VAT_Transac_Rep,
        
        /// <remarks/>
        IC_Partner_Code,
        
        /// <remarks/>
        IC_Partner_Ref_Type,
        
        /// <remarks/>
        Prepmt_CM_Refers_to_Period,
        
        /// <remarks/>
        IC_Partner_Reference,
        
        /// <remarks/>
        Variant_Code,
        
        /// <remarks/>
        Substitution_Available,
        
        /// <remarks/>
        Purchasing_Code,
        
        /// <remarks/>
        Nonstock,
        
        /// <remarks/>
        VAT_Prod_Posting_Group,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Drop_Shipment,
        
        /// <remarks/>
        Special_Order,
        
        /// <remarks/>
        Return_Reason_Code,
        
        /// <remarks/>
        Location_Code,
        
        /// <remarks/>
        Bin_Code,
        
        /// <remarks/>
        Reserve,
        
        /// <remarks/>
        Quantity,
        
        /// <remarks/>
        Qty_to_Assemble_to_Order,
        
        /// <remarks/>
        Reserved_Quantity,
        
        /// <remarks/>
        Unit_of_Measure_Code,
        
        /// <remarks/>
        Unit_of_Measure,
        
        /// <remarks/>
        Unit_Cost_LCY,
        
        /// <remarks/>
        SalesPriceExist,
        
        /// <remarks/>
        Unit_Price,
        
        /// <remarks/>
        Line_Amount,
        
        /// <remarks/>
        SalesLineDiscExists,
        
        /// <remarks/>
        Line_Discount_Percent,
        
        /// <remarks/>
        Line_Discount_Amount,
        
        /// <remarks/>
        Prepayment_Percent,
        
        /// <remarks/>
        Prepmt_Line_Amount,
        
        /// <remarks/>
        Prepmt_Amt_Inv,
        
        /// <remarks/>
        Allow_Invoice_Disc,
        
        /// <remarks/>
        Inv_Discount_Amount,
        
        /// <remarks/>
        Qty_to_Ship,
        
        /// <remarks/>
        Quantity_Shipped,
        
        /// <remarks/>
        Qty_to_Invoice,
        
        /// <remarks/>
        Quantity_Invoiced,
        
        /// <remarks/>
        Prepmt_Amt_to_Deduct,
        
        /// <remarks/>
        Prepmt_Amt_Deducted,
        
        /// <remarks/>
        Allow_Item_Charge_Assignment,
        
        /// <remarks/>
        Qty_to_Assign,
        
        /// <remarks/>
        Qty_Assigned,
        
        /// <remarks/>
        Requested_Delivery_Date,
        
        /// <remarks/>
        Promised_Delivery_Date,
        
        /// <remarks/>
        Planned_Delivery_Date,
        
        /// <remarks/>
        Planned_Shipment_Date,
        
        /// <remarks/>
        Shipment_Date,
        
        /// <remarks/>
        Shipping_Agent_Code,
        
        /// <remarks/>
        Shipping_Agent_Service_Code,
        
        /// <remarks/>
        Shipping_Time,
        
        /// <remarks/>
        Work_Type_Code,
        
        /// <remarks/>
        Whse_Outstanding_Qty,
        
        /// <remarks/>
        Whse_Outstanding_Qty_Base,
        
        /// <remarks/>
        ATO_Whse_Outstanding_Qty,
        
        /// <remarks/>
        ATO_Whse_Outstd_Qty_Base,
        
        /// <remarks/>
        Outbound_Whse_Handling_Time,
        
        /// <remarks/>
        Blanket_Order_No,
        
        /// <remarks/>
        Blanket_Order_Line_No,
        
        /// <remarks/>
        FA_Posting_Date,
        
        /// <remarks/>
        Depr_until_FA_Posting_Date,
        
        /// <remarks/>
        Depreciation_Book_Code,
        
        /// <remarks/>
        Use_Duplication_List,
        
        /// <remarks/>
        Duplicate_in_Depreciation_Book,
        
        /// <remarks/>
        Appl_from_Item_Entry,
        
        /// <remarks/>
        Appl_to_Item_Entry,
        
        /// <remarks/>
        Deferral_Code,
        
        /// <remarks/>
        Shortcut_Dimension_1_Code,
        
        /// <remarks/>
        Shortcut_Dimension_2_Code,
        
        /// <remarks/>
        ShortcutDimCode_x005B_3_x005D_,
        
        /// <remarks/>
        ShortcutDimCode_x005B_4_x005D_,
        
        /// <remarks/>
        ShortcutDimCode_x005B_5_x005D_,
        
        /// <remarks/>
        ShortcutDimCode_x005B_6_x005D_,
        
        /// <remarks/>
        ShortcutDimCode_x005B_7_x005D_,
        
        /// <remarks/>
        ShortcutDimCode_x005B_8_x005D_,
        
        /// <remarks/>
        Document_No,
        
        /// <remarks/>
        Line_No,
        
        /// <remarks/>
        Invoice_Discount_Amount,
        
        /// <remarks/>
        Invoice_Disc_Pct,
        
        /// <remarks/>
        Total_Amount_Excl_VAT,
        
        /// <remarks/>
        Total_VAT_Amount,
        
        /// <remarks/>
        Total_Amount_Incl_VAT,
        
        /// <remarks/>
        RefreshTotals,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesOrderLInes Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesOrderLInes)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesOrderLInes Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesOrderLInes)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesOrderLInes[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesOrderLInes[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesOrderLInes SalesOrderLInes {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesOrderLInes)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void CreateMultipleCompletedEventHandler(object sender, CreateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesOrderLInes[] SalesOrderLInes_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesOrderLInes[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesOrderLInes SalesOrderLInes {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesOrderLInes)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SalesOrderLInes[] SalesOrderLInes_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SalesOrderLInes[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591