//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 07/05/2015 10.06.29
namespace NAVB2BService.NAV_ODATA
{
    
    /// <summary>
    /// There are no comments for NAV in the schema.
    /// </summary>
    public partial class NAV : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new NAV object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public NAV(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "NAV", "NAVB2BService.NAV_ODATA");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("NAVB2BService.NAV_ODATA", global::System.StringComparison.Ordinal))
            {
                return string.Concat("NAV.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for B2BArticoliWeb in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<B2BArticoliWeb> B2BArticoliWeb
        {
            get
            {
                if ((this._B2BArticoliWeb == null))
                {
                    this._B2BArticoliWeb = base.CreateQuery<B2BArticoliWeb>("B2BArticoliWeb");
                }
                return this._B2BArticoliWeb;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<B2BArticoliWeb> _B2BArticoliWeb;
        /// <summary>
        /// There are no comments for B2BClientiWeb in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<B2BClientiWeb> B2BClientiWeb
        {
            get
            {
                if ((this._B2BClientiWeb == null))
                {
                    this._B2BClientiWeb = base.CreateQuery<B2BClientiWeb>("B2BClientiWeb");
                }
                return this._B2BClientiWeb;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<B2BClientiWeb> _B2BClientiWeb;
        /// <summary>
        /// There are no comments for B2BShipAddress in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<B2BShipAddress> B2BShipAddress
        {
            get
            {
                if ((this._B2BShipAddress == null))
                {
                    this._B2BShipAddress = base.CreateQuery<B2BShipAddress>("B2BShipAddress");
                }
                return this._B2BShipAddress;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<B2BShipAddress> _B2BShipAddress;
        /// <summary>
        /// There are no comments for Company in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Company> Company
        {
            get
            {
                if ((this._Company == null))
                {
                    this._Company = base.CreateQuery<Company>("Company");
                }
                return this._Company;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Company> _Company;
        /// <summary>
        /// There are no comments for B2BArticoliWeb in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToB2BArticoliWeb(B2BArticoliWeb b2BArticoliWeb)
        {
            base.AddObject("B2BArticoliWeb", b2BArticoliWeb);
        }
        /// <summary>
        /// There are no comments for B2BClientiWeb in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToB2BClientiWeb(B2BClientiWeb b2BClientiWeb)
        {
            base.AddObject("B2BClientiWeb", b2BClientiWeb);
        }
        /// <summary>
        /// There are no comments for B2BShipAddress in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToB2BShipAddress(B2BShipAddress b2BShipAddress)
        {
            base.AddObject("B2BShipAddress", b2BShipAddress);
        }
        /// <summary>
        /// There are no comments for Company in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCompany(Company company)
        {
            base.AddObject("Company", company);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"NAV\" xmlns=\"http://schemas.microsoft.com/ado/2007/05/edm\"><EntityType" +
                " Name=\"B2BArticoliWeb\"><Key><PropertyRef Name=\"AuxiliaryIndex1\" /><PropertyRef N" +
                "ame=\"AuxiliaryIndex2\" /><PropertyRef Name=\"AuxiliaryIndex3\" /><PropertyRef Name=" +
                "\"AuxiliaryIndex4\" /><PropertyRef Name=\"AuxiliaryIndex5\" /><PropertyRef Name=\"Aux" +
                "iliaryIndex6\" /><PropertyRef Name=\"AuxiliaryIndex7\" /><PropertyRef Name=\"No\" /><" +
                "/Key><Property Name=\"No\" Type=\"Edm.String\" Nullable=\"false\" /><Property Name=\"De" +
                "scription\" Type=\"Edm.String\" /><Property Name=\"Description_2\" Type=\"Edm.String\" " +
                "/><Property Name=\"Base_Unit_of_Measure\" Type=\"Edm.String\" /><Property Name=\"Line" +
                "a\" Type=\"Edm.String\" /><Property Name=\"Quantità_Lotto\" Type=\"Edm.Int32\" /><Prope" +
                "rty Name=\"Last_Date_Modified\" Type=\"Edm.DateTime\" /><Property Name=\"Inventory\" T" +
                "ype=\"Edm.Decimal\" /><Property Name=\"Net_Change\" Type=\"Edm.Decimal\" /><Property N" +
                "ame=\"Last_Movement_Date\" Type=\"Edm.DateTime\" /><Property Name=\"Dimension_Value_C" +
                "ode\" Type=\"Edm.String\" /><Property Name=\"Name\" Type=\"Edm.String\" /><Property Nam" +
                "e=\"AuxiliaryIndex1\" Type=\"Edm.String\" Nullable=\"false\" /><Property Name=\"Auxilia" +
                "ryIndex2\" Type=\"Edm.String\" Nullable=\"false\" /><Property Name=\"AuxiliaryIndex3\" " +
                "Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"AuxiliaryIndex4\" Type=\"Edm.S" +
                "tring\" Nullable=\"false\" /><Property Name=\"AuxiliaryIndex5\" Type=\"Edm.String\" Nul" +
                "lable=\"false\" /><Property Name=\"AuxiliaryIndex6\" Type=\"Edm.String\" Nullable=\"fal" +
                "se\" /><Property Name=\"AuxiliaryIndex7\" Type=\"Edm.String\" Nullable=\"false\" /><Pro" +
                "perty Name=\"Location_Filter_FilterOnly\" Type=\"Edm.String\" /><Property Name=\"Date" +
                "_Filter_FilterOnly\" Type=\"Edm.DateTime\" /></EntityType><EntityType Name=\"B2BClie" +
                "ntiWeb\"><Key><PropertyRef Name=\"AuxiliaryIndex1\" /><PropertyRef Name=\"AuxiliaryI" +
                "ndex2\" /><PropertyRef Name=\"AuxiliaryIndex3\" /><PropertyRef Name=\"No\" /></Key><P" +
                "roperty Name=\"No\" Type=\"Edm.String\" Nullable=\"false\" /><Property Name=\"Name\" Typ" +
                "e=\"Edm.String\" /><Property Name=\"Address\" Type=\"Edm.String\" /><Property Name=\"Ci" +
                "ty\" Type=\"Edm.String\" /><Property Name=\"Post_Code\" Type=\"Edm.String\" /><Property" +
                " Name=\"County\" Type=\"Edm.String\" /><Property Name=\"Country_Region_Code\" Type=\"Ed" +
                "m.String\" /><Property Name=\"Fiscal_Code\" Type=\"Edm.String\" /><Property Name=\"VAT" +
                "_Registration_No\" Type=\"Edm.String\" /><Property Name=\"Email_Ecommerce\" Type=\"Edm" +
                ".String\" /><Property Name=\"ActivadoWeb\" Type=\"Edm.Boolean\" /><Property Name=\"Tip" +
                "ologia_Articoli_Attiva_Web\" Type=\"Edm.String\" /><Property Name=\"Is_Hidden_Price_" +
                "Web\" Type=\"Edm.Boolean\" /><Property Name=\"MD5_B2B_Access_Pwd\" Type=\"Edm.String\" " +
                "/><Property Name=\"MD5_B2B_Price_Pwd\" Type=\"Edm.String\" /><Property Name=\"B2B_Ord" +
                "ers_Blocked\" Type=\"Edm.Boolean\" /><Property Name=\"Dimension_Value_Code\" Type=\"Ed" +
                "m.String\" /><Property Name=\"AuxiliaryIndex1\" Type=\"Edm.Int32\" Nullable=\"false\" /" +
                "><Property Name=\"AuxiliaryIndex2\" Type=\"Edm.String\" Nullable=\"false\" /><Property" +
                " Name=\"AuxiliaryIndex3\" Type=\"Edm.String\" Nullable=\"false\" /></EntityType><Entit" +
                "yType Name=\"B2BShipAddress\"><Key><PropertyRef Name=\"Code\" /><PropertyRef Name=\"C" +
                "ustomer_No\" /></Key><Property Name=\"Customer_No\" Type=\"Edm.String\" Nullable=\"fal" +
                "se\" /><Property Name=\"Code\" Type=\"Edm.String\" Nullable=\"false\" /><Property Name=" +
                "\"Name\" Type=\"Edm.String\" /><Property Name=\"Address\" Type=\"Edm.String\" /><Propert" +
                "y Name=\"City\" Type=\"Edm.String\" /><Property Name=\"Country_Region_Code\" Type=\"Edm" +
                ".String\" /><Property Name=\"Post_Code\" Type=\"Edm.String\" /><Property Name=\"County" +
                "\" Type=\"Edm.String\" /><Property Name=\"Default_Shipment\" Type=\"Edm.Boolean\" /></E" +
                "ntityType><EntityType Name=\"Company\"><Key><PropertyRef Name=\"Name\" /></Key><Prop" +
                "erty Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" /><NavigationProperty Name=\"" +
                "B2BArticoliWeb\" Relationship=\"NAV.Company_B2BArticoliWeb\" ToRole=\"B2BArticoliWeb" +
                "\" FromRole=\"Company\" /><NavigationProperty Name=\"B2BClientiWeb\" Relationship=\"NA" +
                "V.Company_B2BClientiWeb\" ToRole=\"B2BClientiWeb\" FromRole=\"Company\" /><Navigation" +
                "Property Name=\"B2BShipAddress\" Relationship=\"NAV.Company_B2BShipAddress\" ToRole=" +
                "\"B2BShipAddress\" FromRole=\"Company\" /></EntityType><Association Name=\"Company_B2" +
                "BArticoliWeb\"><End Type=\"NAV.Company\" Role=\"Company\" Multiplicity=\"*\" /><End Typ" +
                "e=\"NAV.B2BArticoliWeb\" Role=\"B2BArticoliWeb\" Multiplicity=\"*\" /></Association><A" +
                "ssociation Name=\"Company_B2BClientiWeb\"><End Type=\"NAV.Company\" Role=\"Company\" M" +
                "ultiplicity=\"*\" /><End Type=\"NAV.B2BClientiWeb\" Role=\"B2BClientiWeb\" Multiplicit" +
                "y=\"*\" /></Association><Association Name=\"Company_B2BShipAddress\"><End Type=\"NAV." +
                "Company\" Role=\"Company\" Multiplicity=\"*\" /><End Type=\"NAV.B2BShipAddress\" Role=\"" +
                "B2BShipAddress\" Multiplicity=\"*\" /></Association><EntityContainer Name=\"NAV\" m:I" +
                "sDefaultEntityContainer=\"true\"><EntitySet Name=\"B2BArticoliWeb\" EntityType=\"NAV." +
                "B2BArticoliWeb\" /><EntitySet Name=\"B2BClientiWeb\" EntityType=\"NAV.B2BClientiWeb\"" +
                " /><EntitySet Name=\"B2BShipAddress\" EntityType=\"NAV.B2BShipAddress\" /><EntitySet" +
                " Name=\"Company\" EntityType=\"NAV.Company\" /><AssociationSet Name=\"Company_B2BArti" +
                "coliWeb_B2BArticoliWeb\" Association=\"NAV.Company_B2BArticoliWeb\"><End Role=\"Comp" +
                "any\" EntitySet=\"Company\" /><End Role=\"B2BArticoliWeb\" EntitySet=\"B2BArticoliWeb\"" +
                " /></AssociationSet><AssociationSet Name=\"Company_B2BClientiWeb_B2BClientiWeb\" A" +
                "ssociation=\"NAV.Company_B2BClientiWeb\"><End Role=\"Company\" EntitySet=\"Company\" /" +
                "><End Role=\"B2BClientiWeb\" EntitySet=\"B2BClientiWeb\" /></AssociationSet><Associa" +
                "tionSet Name=\"Company_B2BShipAddress_B2BShipAddress\" Association=\"NAV.Company_B2" +
                "BShipAddress\"><End Role=\"Company\" EntitySet=\"Company\" /><End Role=\"B2BShipAddres" +
                "s\" EntitySet=\"B2BShipAddress\" /></AssociationSet></EntityContainer></Schema></ed" +
                "mx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for NAV.B2BArticoliWeb in the schema.
    /// </summary>
    /// <KeyProperties>
    /// AuxiliaryIndex1
    /// AuxiliaryIndex2
    /// AuxiliaryIndex3
    /// AuxiliaryIndex4
    /// AuxiliaryIndex5
    /// AuxiliaryIndex6
    /// AuxiliaryIndex7
    /// No
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("AuxiliaryIndex1", "AuxiliaryIndex2", "AuxiliaryIndex3", "AuxiliaryIndex4", "AuxiliaryIndex5", "AuxiliaryIndex6", "AuxiliaryIndex7", "No")]
    public partial class B2BArticoliWeb
    {
        /// <summary>
        /// Create a new B2BArticoliWeb object.
        /// </summary>
        /// <param name="no">Initial value of No.</param>
        /// <param name="auxiliaryIndex1">Initial value of AuxiliaryIndex1.</param>
        /// <param name="auxiliaryIndex2">Initial value of AuxiliaryIndex2.</param>
        /// <param name="auxiliaryIndex3">Initial value of AuxiliaryIndex3.</param>
        /// <param name="auxiliaryIndex4">Initial value of AuxiliaryIndex4.</param>
        /// <param name="auxiliaryIndex5">Initial value of AuxiliaryIndex5.</param>
        /// <param name="auxiliaryIndex6">Initial value of AuxiliaryIndex6.</param>
        /// <param name="auxiliaryIndex7">Initial value of AuxiliaryIndex7.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static B2BArticoliWeb CreateB2BArticoliWeb(string no, string auxiliaryIndex1, string auxiliaryIndex2, int auxiliaryIndex3, string auxiliaryIndex4, string auxiliaryIndex5, string auxiliaryIndex6, string auxiliaryIndex7)
        {
            B2BArticoliWeb b2BArticoliWeb = new B2BArticoliWeb();
            b2BArticoliWeb.No = no;
            b2BArticoliWeb.AuxiliaryIndex1 = auxiliaryIndex1;
            b2BArticoliWeb.AuxiliaryIndex2 = auxiliaryIndex2;
            b2BArticoliWeb.AuxiliaryIndex3 = auxiliaryIndex3;
            b2BArticoliWeb.AuxiliaryIndex4 = auxiliaryIndex4;
            b2BArticoliWeb.AuxiliaryIndex5 = auxiliaryIndex5;
            b2BArticoliWeb.AuxiliaryIndex6 = auxiliaryIndex6;
            b2BArticoliWeb.AuxiliaryIndex7 = auxiliaryIndex7;
            return b2BArticoliWeb;
        }
        /// <summary>
        /// There are no comments for Property No in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string No
        {
            get
            {
                return this._No;
            }
            set
            {
                this.OnNoChanging(value);
                this._No = value;
                this.OnNoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _No;
        partial void OnNoChanging(string value);
        partial void OnNoChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Description_2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description_2
        {
            get
            {
                return this._Description_2;
            }
            set
            {
                this.OnDescription_2Changing(value);
                this._Description_2 = value;
                this.OnDescription_2Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description_2;
        partial void OnDescription_2Changing(string value);
        partial void OnDescription_2Changed();
        /// <summary>
        /// There are no comments for Property Base_Unit_of_Measure in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Base_Unit_of_Measure
        {
            get
            {
                return this._Base_Unit_of_Measure;
            }
            set
            {
                this.OnBase_Unit_of_MeasureChanging(value);
                this._Base_Unit_of_Measure = value;
                this.OnBase_Unit_of_MeasureChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Base_Unit_of_Measure;
        partial void OnBase_Unit_of_MeasureChanging(string value);
        partial void OnBase_Unit_of_MeasureChanged();
        /// <summary>
        /// There are no comments for Property Linea in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Linea
        {
            get
            {
                return this._Linea;
            }
            set
            {
                this.OnLineaChanging(value);
                this._Linea = value;
                this.OnLineaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Linea;
        partial void OnLineaChanging(string value);
        partial void OnLineaChanged();
        /// <summary>
        /// There are no comments for Property Quantità_Lotto in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Quantità_Lotto
        {
            get
            {
                return this._Quantità_Lotto;
            }
            set
            {
                this.OnQuantità_LottoChanging(value);
                this._Quantità_Lotto = value;
                this.OnQuantità_LottoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Quantità_Lotto;
        partial void OnQuantità_LottoChanging(global::System.Nullable<int> value);
        partial void OnQuantità_LottoChanged();
        /// <summary>
        /// There are no comments for Property Last_Date_Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> Last_Date_Modified
        {
            get
            {
                return this._Last_Date_Modified;
            }
            set
            {
                this.OnLast_Date_ModifiedChanging(value);
                this._Last_Date_Modified = value;
                this.OnLast_Date_ModifiedChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _Last_Date_Modified;
        partial void OnLast_Date_ModifiedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnLast_Date_ModifiedChanged();
        /// <summary>
        /// There are no comments for Property Inventory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Inventory
        {
            get
            {
                return this._Inventory;
            }
            set
            {
                this.OnInventoryChanging(value);
                this._Inventory = value;
                this.OnInventoryChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Inventory;
        partial void OnInventoryChanging(global::System.Nullable<decimal> value);
        partial void OnInventoryChanged();
        /// <summary>
        /// There are no comments for Property Net_Change in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Net_Change
        {
            get
            {
                return this._Net_Change;
            }
            set
            {
                this.OnNet_ChangeChanging(value);
                this._Net_Change = value;
                this.OnNet_ChangeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Net_Change;
        partial void OnNet_ChangeChanging(global::System.Nullable<decimal> value);
        partial void OnNet_ChangeChanged();
        /// <summary>
        /// There are no comments for Property Last_Movement_Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> Last_Movement_Date
        {
            get
            {
                return this._Last_Movement_Date;
            }
            set
            {
                this.OnLast_Movement_DateChanging(value);
                this._Last_Movement_Date = value;
                this.OnLast_Movement_DateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _Last_Movement_Date;
        partial void OnLast_Movement_DateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnLast_Movement_DateChanged();
        /// <summary>
        /// There are no comments for Property Dimension_Value_Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Dimension_Value_Code
        {
            get
            {
                return this._Dimension_Value_Code;
            }
            set
            {
                this.OnDimension_Value_CodeChanging(value);
                this._Dimension_Value_Code = value;
                this.OnDimension_Value_CodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Dimension_Value_Code;
        partial void OnDimension_Value_CodeChanging(string value);
        partial void OnDimension_Value_CodeChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property AuxiliaryIndex1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AuxiliaryIndex1
        {
            get
            {
                return this._AuxiliaryIndex1;
            }
            set
            {
                this.OnAuxiliaryIndex1Changing(value);
                this._AuxiliaryIndex1 = value;
                this.OnAuxiliaryIndex1Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AuxiliaryIndex1;
        partial void OnAuxiliaryIndex1Changing(string value);
        partial void OnAuxiliaryIndex1Changed();
        /// <summary>
        /// There are no comments for Property AuxiliaryIndex2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AuxiliaryIndex2
        {
            get
            {
                return this._AuxiliaryIndex2;
            }
            set
            {
                this.OnAuxiliaryIndex2Changing(value);
                this._AuxiliaryIndex2 = value;
                this.OnAuxiliaryIndex2Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AuxiliaryIndex2;
        partial void OnAuxiliaryIndex2Changing(string value);
        partial void OnAuxiliaryIndex2Changed();
        /// <summary>
        /// There are no comments for Property AuxiliaryIndex3 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int AuxiliaryIndex3
        {
            get
            {
                return this._AuxiliaryIndex3;
            }
            set
            {
                this.OnAuxiliaryIndex3Changing(value);
                this._AuxiliaryIndex3 = value;
                this.OnAuxiliaryIndex3Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _AuxiliaryIndex3;
        partial void OnAuxiliaryIndex3Changing(int value);
        partial void OnAuxiliaryIndex3Changed();
        /// <summary>
        /// There are no comments for Property AuxiliaryIndex4 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AuxiliaryIndex4
        {
            get
            {
                return this._AuxiliaryIndex4;
            }
            set
            {
                this.OnAuxiliaryIndex4Changing(value);
                this._AuxiliaryIndex4 = value;
                this.OnAuxiliaryIndex4Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AuxiliaryIndex4;
        partial void OnAuxiliaryIndex4Changing(string value);
        partial void OnAuxiliaryIndex4Changed();
        /// <summary>
        /// There are no comments for Property AuxiliaryIndex5 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AuxiliaryIndex5
        {
            get
            {
                return this._AuxiliaryIndex5;
            }
            set
            {
                this.OnAuxiliaryIndex5Changing(value);
                this._AuxiliaryIndex5 = value;
                this.OnAuxiliaryIndex5Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AuxiliaryIndex5;
        partial void OnAuxiliaryIndex5Changing(string value);
        partial void OnAuxiliaryIndex5Changed();
        /// <summary>
        /// There are no comments for Property AuxiliaryIndex6 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AuxiliaryIndex6
        {
            get
            {
                return this._AuxiliaryIndex6;
            }
            set
            {
                this.OnAuxiliaryIndex6Changing(value);
                this._AuxiliaryIndex6 = value;
                this.OnAuxiliaryIndex6Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AuxiliaryIndex6;
        partial void OnAuxiliaryIndex6Changing(string value);
        partial void OnAuxiliaryIndex6Changed();
        /// <summary>
        /// There are no comments for Property AuxiliaryIndex7 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AuxiliaryIndex7
        {
            get
            {
                return this._AuxiliaryIndex7;
            }
            set
            {
                this.OnAuxiliaryIndex7Changing(value);
                this._AuxiliaryIndex7 = value;
                this.OnAuxiliaryIndex7Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AuxiliaryIndex7;
        partial void OnAuxiliaryIndex7Changing(string value);
        partial void OnAuxiliaryIndex7Changed();
        /// <summary>
        /// There are no comments for Property Location_Filter_FilterOnly in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Location_Filter_FilterOnly
        {
            get
            {
                return this._Location_Filter_FilterOnly;
            }
            set
            {
                this.OnLocation_Filter_FilterOnlyChanging(value);
                this._Location_Filter_FilterOnly = value;
                this.OnLocation_Filter_FilterOnlyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Location_Filter_FilterOnly;
        partial void OnLocation_Filter_FilterOnlyChanging(string value);
        partial void OnLocation_Filter_FilterOnlyChanged();
        /// <summary>
        /// There are no comments for Property Date_Filter_FilterOnly in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> Date_Filter_FilterOnly
        {
            get
            {
                return this._Date_Filter_FilterOnly;
            }
            set
            {
                this.OnDate_Filter_FilterOnlyChanging(value);
                this._Date_Filter_FilterOnly = value;
                this.OnDate_Filter_FilterOnlyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _Date_Filter_FilterOnly;
        partial void OnDate_Filter_FilterOnlyChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDate_Filter_FilterOnlyChanged();
    }
    /// <summary>
    /// There are no comments for NAV.B2BClientiWeb in the schema.
    /// </summary>
    /// <KeyProperties>
    /// AuxiliaryIndex1
    /// AuxiliaryIndex2
    /// AuxiliaryIndex3
    /// No
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("AuxiliaryIndex1", "AuxiliaryIndex2", "AuxiliaryIndex3", "No")]
    public partial class B2BClientiWeb
    {
        /// <summary>
        /// Create a new B2BClientiWeb object.
        /// </summary>
        /// <param name="no">Initial value of No.</param>
        /// <param name="auxiliaryIndex1">Initial value of AuxiliaryIndex1.</param>
        /// <param name="auxiliaryIndex2">Initial value of AuxiliaryIndex2.</param>
        /// <param name="auxiliaryIndex3">Initial value of AuxiliaryIndex3.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static B2BClientiWeb CreateB2BClientiWeb(string no, int auxiliaryIndex1, string auxiliaryIndex2, string auxiliaryIndex3)
        {
            B2BClientiWeb b2BClientiWeb = new B2BClientiWeb();
            b2BClientiWeb.No = no;
            b2BClientiWeb.AuxiliaryIndex1 = auxiliaryIndex1;
            b2BClientiWeb.AuxiliaryIndex2 = auxiliaryIndex2;
            b2BClientiWeb.AuxiliaryIndex3 = auxiliaryIndex3;
            return b2BClientiWeb;
        }
        /// <summary>
        /// There are no comments for Property No in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string No
        {
            get
            {
                return this._No;
            }
            set
            {
                this.OnNoChanging(value);
                this._No = value;
                this.OnNoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _No;
        partial void OnNoChanging(string value);
        partial void OnNoChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this._Address = value;
                this.OnAddressChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this._City = value;
                this.OnCityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property Post_Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Post_Code
        {
            get
            {
                return this._Post_Code;
            }
            set
            {
                this.OnPost_CodeChanging(value);
                this._Post_Code = value;
                this.OnPost_CodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Post_Code;
        partial void OnPost_CodeChanging(string value);
        partial void OnPost_CodeChanged();
        /// <summary>
        /// There are no comments for Property County in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string County
        {
            get
            {
                return this._County;
            }
            set
            {
                this.OnCountyChanging(value);
                this._County = value;
                this.OnCountyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _County;
        partial void OnCountyChanging(string value);
        partial void OnCountyChanged();
        /// <summary>
        /// There are no comments for Property Country_Region_Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Country_Region_Code
        {
            get
            {
                return this._Country_Region_Code;
            }
            set
            {
                this.OnCountry_Region_CodeChanging(value);
                this._Country_Region_Code = value;
                this.OnCountry_Region_CodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Country_Region_Code;
        partial void OnCountry_Region_CodeChanging(string value);
        partial void OnCountry_Region_CodeChanged();
        /// <summary>
        /// There are no comments for Property Fiscal_Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Fiscal_Code
        {
            get
            {
                return this._Fiscal_Code;
            }
            set
            {
                this.OnFiscal_CodeChanging(value);
                this._Fiscal_Code = value;
                this.OnFiscal_CodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Fiscal_Code;
        partial void OnFiscal_CodeChanging(string value);
        partial void OnFiscal_CodeChanged();
        /// <summary>
        /// There are no comments for Property VAT_Registration_No in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string VAT_Registration_No
        {
            get
            {
                return this._VAT_Registration_No;
            }
            set
            {
                this.OnVAT_Registration_NoChanging(value);
                this._VAT_Registration_No = value;
                this.OnVAT_Registration_NoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _VAT_Registration_No;
        partial void OnVAT_Registration_NoChanging(string value);
        partial void OnVAT_Registration_NoChanged();
        /// <summary>
        /// There are no comments for Property Email_Ecommerce in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Email_Ecommerce
        {
            get
            {
                return this._Email_Ecommerce;
            }
            set
            {
                this.OnEmail_EcommerceChanging(value);
                this._Email_Ecommerce = value;
                this.OnEmail_EcommerceChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Email_Ecommerce;
        partial void OnEmail_EcommerceChanging(string value);
        partial void OnEmail_EcommerceChanged();
        /// <summary>
        /// There are no comments for Property ActivadoWeb in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> ActivadoWeb
        {
            get
            {
                return this._ActivadoWeb;
            }
            set
            {
                this.OnActivadoWebChanging(value);
                this._ActivadoWeb = value;
                this.OnActivadoWebChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _ActivadoWeb;
        partial void OnActivadoWebChanging(global::System.Nullable<bool> value);
        partial void OnActivadoWebChanged();
        /// <summary>
        /// There are no comments for Property Tipologia_Articoli_Attiva_Web in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Tipologia_Articoli_Attiva_Web
        {
            get
            {
                return this._Tipologia_Articoli_Attiva_Web;
            }
            set
            {
                this.OnTipologia_Articoli_Attiva_WebChanging(value);
                this._Tipologia_Articoli_Attiva_Web = value;
                this.OnTipologia_Articoli_Attiva_WebChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Tipologia_Articoli_Attiva_Web;
        partial void OnTipologia_Articoli_Attiva_WebChanging(string value);
        partial void OnTipologia_Articoli_Attiva_WebChanged();
        /// <summary>
        /// There are no comments for Property Is_Hidden_Price_Web in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> Is_Hidden_Price_Web
        {
            get
            {
                return this._Is_Hidden_Price_Web;
            }
            set
            {
                this.OnIs_Hidden_Price_WebChanging(value);
                this._Is_Hidden_Price_Web = value;
                this.OnIs_Hidden_Price_WebChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _Is_Hidden_Price_Web;
        partial void OnIs_Hidden_Price_WebChanging(global::System.Nullable<bool> value);
        partial void OnIs_Hidden_Price_WebChanged();
        /// <summary>
        /// There are no comments for Property MD5_B2B_Access_Pwd in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MD5_B2B_Access_Pwd
        {
            get
            {
                return this._MD5_B2B_Access_Pwd;
            }
            set
            {
                this.OnMD5_B2B_Access_PwdChanging(value);
                this._MD5_B2B_Access_Pwd = value;
                this.OnMD5_B2B_Access_PwdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MD5_B2B_Access_Pwd;
        partial void OnMD5_B2B_Access_PwdChanging(string value);
        partial void OnMD5_B2B_Access_PwdChanged();
        /// <summary>
        /// There are no comments for Property MD5_B2B_Price_Pwd in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MD5_B2B_Price_Pwd
        {
            get
            {
                return this._MD5_B2B_Price_Pwd;
            }
            set
            {
                this.OnMD5_B2B_Price_PwdChanging(value);
                this._MD5_B2B_Price_Pwd = value;
                this.OnMD5_B2B_Price_PwdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MD5_B2B_Price_Pwd;
        partial void OnMD5_B2B_Price_PwdChanging(string value);
        partial void OnMD5_B2B_Price_PwdChanged();
        /// <summary>
        /// There are no comments for Property B2B_Orders_Blocked in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> B2B_Orders_Blocked
        {
            get
            {
                return this._B2B_Orders_Blocked;
            }
            set
            {
                this.OnB2B_Orders_BlockedChanging(value);
                this._B2B_Orders_Blocked = value;
                this.OnB2B_Orders_BlockedChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _B2B_Orders_Blocked;
        partial void OnB2B_Orders_BlockedChanging(global::System.Nullable<bool> value);
        partial void OnB2B_Orders_BlockedChanged();
        /// <summary>
        /// There are no comments for Property Dimension_Value_Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Dimension_Value_Code
        {
            get
            {
                return this._Dimension_Value_Code;
            }
            set
            {
                this.OnDimension_Value_CodeChanging(value);
                this._Dimension_Value_Code = value;
                this.OnDimension_Value_CodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Dimension_Value_Code;
        partial void OnDimension_Value_CodeChanging(string value);
        partial void OnDimension_Value_CodeChanged();
        /// <summary>
        /// There are no comments for Property AuxiliaryIndex1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int AuxiliaryIndex1
        {
            get
            {
                return this._AuxiliaryIndex1;
            }
            set
            {
                this.OnAuxiliaryIndex1Changing(value);
                this._AuxiliaryIndex1 = value;
                this.OnAuxiliaryIndex1Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _AuxiliaryIndex1;
        partial void OnAuxiliaryIndex1Changing(int value);
        partial void OnAuxiliaryIndex1Changed();
        /// <summary>
        /// There are no comments for Property AuxiliaryIndex2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AuxiliaryIndex2
        {
            get
            {
                return this._AuxiliaryIndex2;
            }
            set
            {
                this.OnAuxiliaryIndex2Changing(value);
                this._AuxiliaryIndex2 = value;
                this.OnAuxiliaryIndex2Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AuxiliaryIndex2;
        partial void OnAuxiliaryIndex2Changing(string value);
        partial void OnAuxiliaryIndex2Changed();
        /// <summary>
        /// There are no comments for Property AuxiliaryIndex3 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AuxiliaryIndex3
        {
            get
            {
                return this._AuxiliaryIndex3;
            }
            set
            {
                this.OnAuxiliaryIndex3Changing(value);
                this._AuxiliaryIndex3 = value;
                this.OnAuxiliaryIndex3Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AuxiliaryIndex3;
        partial void OnAuxiliaryIndex3Changing(string value);
        partial void OnAuxiliaryIndex3Changed();
    }
    /// <summary>
    /// There are no comments for NAV.B2BShipAddress in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Code
    /// Customer_No
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Code", "Customer_No")]
    public partial class B2BShipAddress
    {
        /// <summary>
        /// Create a new B2BShipAddress object.
        /// </summary>
        /// <param name="customer_No">Initial value of Customer_No.</param>
        /// <param name="code">Initial value of Code.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static B2BShipAddress CreateB2BShipAddress(string customer_No, string code)
        {
            B2BShipAddress b2BShipAddress = new B2BShipAddress();
            b2BShipAddress.Customer_No = customer_No;
            b2BShipAddress.Code = code;
            return b2BShipAddress;
        }
        /// <summary>
        /// There are no comments for Property Customer_No in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Customer_No
        {
            get
            {
                return this._Customer_No;
            }
            set
            {
                this.OnCustomer_NoChanging(value);
                this._Customer_No = value;
                this.OnCustomer_NoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Customer_No;
        partial void OnCustomer_NoChanging(string value);
        partial void OnCustomer_NoChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this._Code = value;
                this.OnCodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Code;
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this._Address = value;
                this.OnAddressChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this._City = value;
                this.OnCityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property Country_Region_Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Country_Region_Code
        {
            get
            {
                return this._Country_Region_Code;
            }
            set
            {
                this.OnCountry_Region_CodeChanging(value);
                this._Country_Region_Code = value;
                this.OnCountry_Region_CodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Country_Region_Code;
        partial void OnCountry_Region_CodeChanging(string value);
        partial void OnCountry_Region_CodeChanged();
        /// <summary>
        /// There are no comments for Property Post_Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Post_Code
        {
            get
            {
                return this._Post_Code;
            }
            set
            {
                this.OnPost_CodeChanging(value);
                this._Post_Code = value;
                this.OnPost_CodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Post_Code;
        partial void OnPost_CodeChanging(string value);
        partial void OnPost_CodeChanged();
        /// <summary>
        /// There are no comments for Property County in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string County
        {
            get
            {
                return this._County;
            }
            set
            {
                this.OnCountyChanging(value);
                this._County = value;
                this.OnCountyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _County;
        partial void OnCountyChanging(string value);
        partial void OnCountyChanged();
        /// <summary>
        /// There are no comments for Property Default_Shipment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> Default_Shipment
        {
            get
            {
                return this._Default_Shipment;
            }
            set
            {
                this.OnDefault_ShipmentChanging(value);
                this._Default_Shipment = value;
                this.OnDefault_ShipmentChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _Default_Shipment;
        partial void OnDefault_ShipmentChanging(global::System.Nullable<bool> value);
        partial void OnDefault_ShipmentChanged();
    }
    /// <summary>
    /// There are no comments for NAV.Company in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Name
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Name")]
    public partial class Company
    {
        /// <summary>
        /// Create a new Company object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Company CreateCompany(string name)
        {
            Company company = new Company();
            company.Name = name;
            return company;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for B2BArticoliWeb in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<B2BArticoliWeb> B2BArticoliWeb
        {
            get
            {
                return this._B2BArticoliWeb;
            }
            set
            {
                if ((value != null))
                {
                    this._B2BArticoliWeb = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<B2BArticoliWeb> _B2BArticoliWeb = new global::System.Collections.ObjectModel.Collection<B2BArticoliWeb>();
        /// <summary>
        /// There are no comments for B2BClientiWeb in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<B2BClientiWeb> B2BClientiWeb
        {
            get
            {
                return this._B2BClientiWeb;
            }
            set
            {
                if ((value != null))
                {
                    this._B2BClientiWeb = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<B2BClientiWeb> _B2BClientiWeb = new global::System.Collections.ObjectModel.Collection<B2BClientiWeb>();
        /// <summary>
        /// There are no comments for B2BShipAddress in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<B2BShipAddress> B2BShipAddress
        {
            get
            {
                return this._B2BShipAddress;
            }
            set
            {
                if ((value != null))
                {
                    this._B2BShipAddress = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<B2BShipAddress> _B2BShipAddress = new global::System.Collections.ObjectModel.Collection<B2BShipAddress>();
    }
}
